config/routes.rb
Rails.application.routes.draw do
  resources :evaluations
  get 'home/index'
  resources :questionnaires

  get '/rgpd', to: 'application#_rgpd'

  devise_for :users
  root 'home#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
  belongs_to :questionnaire

  validates_presence_of :value1, :message => "^Veuillez saisir une réponse pour ce champs"
  validates_presence_of :value2, :message => "^Veuillez saisir une réponse pour ce champs"
  validates_presence_of :value3, :message => "^Veuillez saisir une réponse pour ce champs"
  validates_presence_of :value4, :message => "^Veuillez saisir une réponse pour ce champs"
  validates_presence_of :value5, :message => "^Veuillez saisir une réponse pour ce champs"

  before_save :compute_score

  def value1_ponderated
    1.0 * value1 * questionnaire.importance1 / 10.0
  end

  def value2_ponderated
    1.0 * value2 * questionnaire.importance2 / 10.0
  end

  def value3_ponderated
    1.0 * value3 * questionnaire.importance3 / 10.0
  end

  def value4_ponderated
    1.0 * value4 * questionnaire.importance4 / 10.0
  end

  def value5_ponderated
    1.0 * value5 * questionnaire.importance5 / 10.0
  end

  def to_s
    "Evaluation du #{created_at.strftime '%d/%m/%Y'}"
  end

  

  protected

  def compute_score
    self.score = value1_ponderated + value2_ponderated + value3_ponderated + value4_ponderated + value5_ponderated
  end
end

app/models/questionnaire.rb
class Questionnaire < ApplicationRecord
  belongs_to :user
  has_many :evaluations

  # Permet de définir que les champs doivent être remplis
  validates_presence_of :question1, :message => "^Veuillez saisir une réponse pour ce champs"
  validates_presence_of :question2, :message => "^Veuillez saisir une réponse pour ce champs"
  validates_presence_of :question3, :message => "^Veuillez saisir une réponse pour ce champs"
  validates_presence_of :question4, :message => "^Veuillez saisir une réponse pour ce champs"
  validates_presence_of :question5, :message => "^Veuillez saisir une réponse pour ce champs"
  validates_presence_of :importance1, :message => "^Veuillez saisir un nombre entre 1 et 96"
  validates_presence_of :importance2, :message => "^Veuillez saisir un nombre entre 1 et 96"
  validates_presence_of :importance3, :message => "^Veuillez saisir un nombre entre 1 et 96"
  validates_presence_of :importance4, :message => "^Veuillez saisir un nombre entre 1 et 96"
  validates_presence_of :importance5, :message => "^Veuillez saisir un nombre entre 1 et 96"
  
  def to_s
    "Questionnaire du #{created_at.strftime '%d/%m/%Y'}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable

  has_many :questionnaires

  validates_presence_of :email, :message => "^Veuillez saisir une adresse mail"
  validates_presence_of :password, :message => "^Veuillez saisir un mot de passe"
  validates_presence_of :password_confirmation, :message => "^Veuillez vérifier un mot de passe"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_devise_parameters, if: :devise_controller?

	def configure_devise_parameters
		devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name,:last_name, :date_of_birth, :name, :email, :password, :password_confirmation)}
	end

	def _rgpd
		
	end
end

app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_evaluation, only: [:show, :edit, :update, :destroy]

  # GET /evaluations
  # GET /evaluations.json
  def index
    @evaluations = Evaluation.all
  end

  # GET /evaluations/1
  # GET /evaluations/1.json
  def show
    @questionnaire = @evaluation.questionnaire
  end

  # GET /evaluations/new
  def new
    @evaluation = Evaluation.new
    @evaluation.questionnaire_id = params[:questionnaire_id]
    @questionnaire = Questionnaire.find(params[:questionnaire_id])
  end

  # GET /evaluations/1/edit
  def edit
  end

  # POST /evaluations
  # POST /evaluations.json
  def create
    @evaluation = Evaluation.new(evaluation_params)
    respond_to do |format|
      if @evaluation.save
        format.html { redirect_to evaluation_path(id: @evaluation.id) }
        format.json { render :show, status: :created, location: @evaluation }
      else
        format.html { render :new }
        format.json { render json: @evaluation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evaluations/1
  # PATCH/PUT /evaluations/1.json
  def update
    respond_to do |format|
      if @evaluation.update(evaluation_params)
        format.html { redirect_to @evaluation, notice: 'Evaluation was successfully updated.' }
        format.json { render :show, status: :ok, location: @evaluation }
      else
        format.html { render :edit }
        format.json { render json: @evaluation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evaluations/1
  # DELETE /evaluations/1.json
  def destroy
    @evaluation.destroy
    respond_to do |format|
      format.html { redirect_to evaluations_url, notice: 'Evaluation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_evaluation
      @evaluation = Evaluation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def evaluation_params
      params.require(:evaluation).permit(:questionnaire_id, :value1, :value2, :value3, :value4, :value5, :score)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/questionnaires_controller.rb
class QuestionnairesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_questionnaire, only: [:show, :edit, :update, :destroy]

  # GET /questionnaires
  # GET /questionnaires.json
  def index
    @questionnaires = current_user.questionnaires
  end

  # GET /questionnaires/1
  # GET /questionnaires/1.json
  def show
  end

  # GET /questionnaires/new
  def new
    @questionnaire = Questionnaire.new

  end

  # GET /questionnaires/1/edit
  def edit
  end

  # POST /questionnaires
  # POST /questionnaires.json
  def create
    @questionnaire = Questionnaire.new(questionnaire_params)
    @questionnaire.user = current_user

    respond_to do |format|
      if @questionnaire.save
        format.html { redirect_to new_evaluation_path(questionnaire_id: @questionnaire.id), notice: 'Questionnaire was successfully created.' }
        format.json { render :show, status: :created, location: @questionnaire }
      else
        format.html { render :new }
        format.json { render json: @questionnaire.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questionnaires/1
  # PATCH/PUT /questionnaires/1.json
  def update
    respond_to do |format|
      if @questionnaire.update(questionnaire_params)
        format.html { redirect_to @questionnaire, notice: 'Questionnaire was successfully updated.' }
        format.json { render :show, status: :ok, location: @questionnaire }
      else
        format.html { render :edit }
        format.json { render json: @questionnaire.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questionnaires/1
  # DELETE /questionnaires/1.json
  def destroy
    @questionnaire.destroy
    respond_to do |format|
      format.html { redirect_to questionnaires_url, notice: 'Questionnaire was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_questionnaire
      @questionnaire = Questionnaire.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def questionnaire_params
      params.require(:questionnaire).permit(:user_id, :question1, :question2, :question3, :question4, :question5, :importance1, :importance2, :importance3, :importance4, :importance5)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/evaluations_helper.rb
module EvaluationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questionnaires_helper.rb
module QuestionnairesHelper
end

app/views/application/_footer.html.erb
<footer class="page-footer mt-4 bg-light shadow-lg p-1">

<div class="container">
    <div class="text-center text-md-left">
        <div class="row mt-5">
            <div class="col-md-4 mb-3 pb-3 footer-brand">
                <%= image_tag "logo-footer.png", class: 'img-fluid footer-brand-logo' %>
            </div>
            <div class="col-md-4 mb-3 pb-3">
                <h5 class="text-uppercase font-weight-bold">Qui sommes nous ?</h5><br>
                <p><strong>L’Atelier de l’Évaluation</strong></p>
                <p>6 rue de la Croix 86600 SAINT-SAUVANT</p>
            </div>
            <div class="col-md-4 mb-3 pb-3">
                <h5 class="text-uppercase font-weight-bold">Nous contacter</h5><br>
                <p><strong>Téléphone/Fax :</strong> 05.49.01.06.03 </p>
                <p><strong>Courriel :</strong> contact@atelierdelevaluation.fr</p>
            </div>
        </div>
    </div>
    <div class="footer-copyright text-center py-3 border-top">

        <p>
            <%= link_to 'Mentions légales', rgpd_path, class: 'rgpd' %>
            | Tous droits réservés à l'<strong>IUT MMI Bordeaux</strong>
            | 2020
        </p>

    </div>
</div>
<!-- Copyright -->

<!-- Copyright -->
</footer>

app/views/application/_rgpd.html.erb
<h1 class="text-center mt-5 py-5">Mentions légales</h1>

<div class="rgpd_text">
	<div>
		<p> Mise à jour le 10 Avril 2020</p>
		<h2 class="rgpd">Conditions Générales d'Utilisation</h2>
		<h3 class="rgpd_italic">Préambule</h3>
		<p>
			Les présentes Conditions Générales d'Utilisation décrivent les termes et conditions dans lesquels l’équipe d’Evatco fournit un service de calcul et de suivi de qualité de vie.
<br>
			L’accès à ce service est subordonné au respect des présentes “Conditions Générales d’Utilisation”. Tout utilisateur de la plateforme souhaitant y accéder, doit avoir pris connaissance préalablement de nos “Conditions Générales d’Utilisation” et s'engage à les respecter sans réserve.
		</p>
		<h4 class="rgpd_bold">Article 1 – Obligations de l’utilisateur</h4>
		<p>
			Il est rappelé que seul l’utilisateur est propriétaire du contenu qu’il rentre sur la plateforme. Aucune donnée ne sera traitée par Evatco sauf demande écrite de votre part.
		</p>
		<h4 class="rgpd_bold">Article 2 – Coopérations avec les autorités publiques</h4>
		<p>
			Evatco a l'obligation légale de coopérer avec les autorités publiques qui souhaiteraient effectuer des vérifications relatives aux contenus ou à l'identité des utilisateurs du service, et s'y soumet. Les utilisateurs du service se déclarent informés qu’Evatco peut être délivrée de son secret professionnel dans les conditions prévues par l'article 6 de la loi du 21 Juin 2004, et y consentent. Evatco ne saurait être tenue pour responsable des contenus qu’elle héberge.
		</p>
	</div>

	<div>
		<h2 class="rgpd">La protection des données personnelles</h2>
		<h3 class="rgpd_italic">Vos données</h3>
		<h4 class="rgpd_bold">Données que vous renseignez</h4>
		<p>
			À votre inscription sur <a href="https://qualiviscope.herokuapp.com" style="color: black; text-decoration: underline;">https://qualiviscope.herokuapp.com</a>, vous renseignez des données de base (adresse e-mail, mot de passe) et des données à caractère personnel (afin de mesurer votre qualité de vie). Nous stockons ces données de manière sécurisée pour tout naturellement vous donner accès à notre service de suivi. 
			Votre adresse e-mail n’est jamais automatiquement partagée avec des organismes externes.
		</p>
		<h4 class="rgpd_bold">Droits d’accès, de rectification et d’opposition</h4>
	 	<p>
			Conformément au règlement général sur la protection des données (RGPD) du 25 Mai 2018, vous disposez d’un droit d’accès, de rectification et d’opposition des données vous concernant. Vous pouvez exercer ces droits par e-mail ou par courrier à l’adresse suivante :
			L’Atelier de l’Évaluation 6 rue de la Croix 86600 SAINT-SAUVANT formation@atelierdelevaluation.fr <br>

			Depuis ce 25 mai 2018, en application du règlement 2016/679 du 27 avril 2016, vous pourrez également exercer votre droit à la limitation du traitement, à l’effacement de vos données, à la portabilité des données et à ne pas faire l’objet d’une décision individuelle automatisée, y compris le profilage.
			Dans un souci de confidentialité et de protection des données personnelles, une copie d’un titre d’identité signé devra être intégrée à la demande. En cas de réponse insatisfaisante, vous avez la possibilité de saisir la CNIL.
		</p>
	</div>

	<div>
		<h2 class="rgpd">Mentions Légales</h2>
		<h4 class="rgpd_bold">Pour vos réclamations, merci de les adresser à </h4>
		
	<ul class="list-group list-group-flush">
		<li class="list-group-item">
			<div class="row my-3">
				<div class="col-md-4 d-flex align-items-center">
					<p>
						L’Atelier de l’Évaluation <br>
						6 rue de la Croix 86600 SAINT-SAUVANT <br>
						Tel/Fax: 05.49.01.06.03 <br>
						formation@atelierdelevaluation.fr
					</p>
				</div>
				<div class="col-md-4 d-flex align-items-center">
					<p style="text-align: left !important;">
						SCOP SARL au Capital de 10 100,00 € <br>
						RCS POITIERS 478 187 131  -  APE : 8559A <br>
						Numéro TVA intracommunautaire : FR81478187131 <br>
						Organisme de formation enregistré DIRECCTE / DRTEFP sous le N°: 54860100186 <br> 
						Organisme de formation référencé au DATADOCK sous le N° : 0019466 <br>
						Directeur de la publication : Claude WOLTER
					</p>
				</div>
				<div class="col-md-4 d-flex align-items-center justify-content-center">
					<%= image_tag "logo-footer.png", class: 'img-fluid footer-brand-logo' %>
				</div>
			</div>
		</li>
		<li class="list-group-item my-4">
			<div class="row">
				<div class="col-md-6">
					<p>
						Le site est hébergé par <strong>HEROKU</strong> <br>
						<a href="https://www.heroku.com" style="color: black; text-decoration: underline;">https://www.heroku.com</a><br>
						Adresse : 50 Fremont St.Suite 300, San Francisco, CA 94105
					</p>
				</div>
				<div class="col-md-6">
					<p>
						Le site a été entièrement conçu par l'<strong>IUT Bordeaux Montaigne</strong> <br>
						<a href="http://www.iut.u-bordeaux-montaigne.fr" style="color: black; text-decoration: underline;">http://www.iut.u-bordeaux-montaigne.fr</a><br>
						Adresse : 1 Rue Jacques Ellul, 33800 Bordeaux <br>
					</p>
				</div>
			</div>
		</li>
	</ul>
		
		

		<!-- <div class="row">
			<div class="col-md-4">
				<ul class="list-group list-group-flush">
					<li class="list-group-item">Julien Berdah</li> 
					<li class="list-group-item">Nathan Braud</li>
					<li class="list-group-item">Théo Capitaine</li>
					<li class="list-group-item">Mathis Chantereau</li>
				</ul>
			</div>

			<div class="col-md-4">
				<ul class="list-group list-group-flush">
					<li class="list-group-item">Jules Lebret</li>
					<li class="list-group-item">Lucas Ngouembe</li>
					<li class="list-group-item">Stephen Nicolas</li>
					<li class="list-group-item">Marie Simonek</li>
				</ul>
			</div>
			<div class="col-md-4">
				<ul class="list-group list-group-flush">
					<li class="list-group-item">Yohann Tonnere</li>
					<li class="list-group-item">Pierre-Alexis Velain</li>
					<li class="list-group-item">Eva Vandererve</li>
				</ul>
			</div>
		</div>	 -->	
	</div>
</div>

app/views/evaluations/edit.html.erb
<%= render 'form', evaluation: @evaluation %>

<%= link_to 'Show', @evaluation %> |
<%= link_to 'Back', evaluations_path %>

app/views/evaluations/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center my-5">Mes évaluations</h1>

<% @evaluation.each do |evaluation| %>
<div class="table-responsive">
    <table class="table table-bordered table-striped">
        <thead class="thead-dark">
            <th colspan="6">
                <div class="d-flex justify-content-between align-items-center">
                    Evaluation n°<%= evaluation.id %>
                    <div>
                    <%= link_to 'Voir', evaluation, class: 'btn btn-success rounded-0' %>
                    <%= link_to 'Editer', edit_evaluation_path(evaluation), class: 'btn btn-primary rounded-0' %>
                    <%= link_to 'Supprimer', evaluation, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger rounded-0' %>
                    </div>
                </div>
            </th>
        </thead>
        <thead>
            <tr>
                <th scope="col">Valeur 1</th>
                <th scope="col">Valeur 2</th>
                <th scope="col">Valeur 3</th>
                <th scope="col">Valeur 4</th>
                <th scope="col">Valeur 5</th>
                <th scope="col">Score</th>
            </tr>
        </thead>

        <tbody>
            <tr>
                <td><%= evaluation.value1 %></td>
                <td><%= evaluation.value2 %></td>
                <td><%= evaluation.value3 %></td>
                <td><%= evaluation.value4 %></td>
                <td><%= evaluation.value5 %></td>
                <th scope="row"><%= evaluation.score %></th>
            </tr>
        </tbody>
    </table>
</div>
<% end %>



<div class="form-actions mt-5 text-center">
    <%= link_to 'New Evaluation', new_evaluation_path, class: "btn btn-dark rounded-pill" %>
</div>

app/views/evaluations/new.html.erb
<%= render 'form', evaluation: @evaluation %>

app/views/evaluations/show.html.erb
<h1 class="col mt-3 text-center evaluation-date">Mon score de qualité de vie</h1>


<div class="row mb-5 mt-5" style="min-height: 50vh;">
  <div class='chartscore d-flex justify-content-center align-item-center flex-column col-md-6'>
    <div class='total'>
      <div class='note_cam'>
        <div id="chartdiv"></div>
        <div id="charttotal"></div>
      </div>
        <div id='affichage'><%= @evaluation.score %></div>
      </div>
  </div>



  <div class="col-md-6 d-flex justify-content-center align-item-center flex-column">
    <p class="display-4">Votre qualiviscore est de :</p>
    <p class="display-2"><%= @evaluation.score %>/100</p>
    <div>
        <a class="btn btn-dark " href="" onclick="javascript:window.print()">Imprimer mes résultats</a>
    </div>
  </div>
</div>

<%
# https://github.com/dvandersluis/amcharts.rb
%>

<script src="https://www.amcharts.com/lib/4/core.js"></script>
<script src="https://www.amcharts.com/lib/4/charts.js"></script>
<script src="https://www.amcharts.com/lib/4/themes/material.js"></script>
<script src="https://www.amcharts.com/lib/4/themes/animated.js"></script>

<script type="text/javascript">
$(function() {
  // Themes begin
  am4core.useTheme(am4themes_material);
  am4core.useTheme(am4themes_animated);
  // Themes end

  // Create chart

    var chart = am4core.create("chartdiv", am4charts.PieChart);
    chart.hiddenState.properties.opacity = 0; // this creates initial fade-in
    chart.innerRadius = am4core.percent(18);
    var charttot = am4core.create("charttotal", am4charts.PieChart);
    charttot.hiddenState.properties.opacity = 0; // this creates initial fade-in
    charttot.innerRadius = am4core.percent(10);


if (window.matchMedia("(max-width: 768px)").matches)
    {
        chart.innerRadius = am4core.percent(25);
        charttot.innerRadius = am4core.percent(20);
    }





  var note1 = <%= @evaluation.value1 %>;
  var note2 = <%= @evaluation.value2 %>;
  var note3 = <%= @evaluation.value3 %>;
  var note4 = <%= @evaluation.value4 %>;
  var note5 = <%= @evaluation.value5 %>;


  var val1 = <%= @questionnaire.importance1 %>;
  var val2 = <%= @questionnaire.importance2 %>;
  var val3 = <%= @questionnaire.importance3 %>;
  var val4 = <%= @questionnaire.importance4 %>;
  var val5 = <%= @questionnaire.importance5 %>;

  console.log(val1)

  chart.data = [

    {
      choice: "<%= @questionnaire.question1 %> ",
      part: val1,
      note: note1,
      "color": am4core.color('#384B9B')
    },
    {
      choice: "<%= @questionnaire.question2 %> ",
      part: val2,
      note: note2,
      "color": am4core.color('#ED6B80')
    },
    {
      choice: "<%= @questionnaire.question3 %> ",
      part: val3,
      note: note3,
      "color": am4core.color('#F8CF62')
    },
    {
      choice: "<%= @questionnaire.question4 %> ",
      part: val4,
      note: note4,
      "color": am4core.color('#81B3A3')
    },
    {
      choice: "<%= @questionnaire.question5 %> ",
      part: val5,
      note: note5,
      "color": am4core.color('#B6D239')
    },

  ];

  charttot.data = [

    {
      choice: "<%= @questionnaire.question1 %> ",
      part: val1,
      note: 1,
      "color": am4core.color('#384B9B')
    },
    {
      choice: "<%= @questionnaire.question2 %> ",
      part: val2,
      note: 1,
      "color": am4core.color('#ED6B80')
    },
    {
      choice: "<%= @questionnaire.question3 %> ",
      part: val3,
      note: 1,
      "color": am4core.color('#F8CF62')
    },
    {
      choice: "<%= @questionnaire.question4 %> ",
      part: val4,
      note: 1,
      "color": am4core.color('#81B3A3')
    },
    {
      choice: "<%= @questionnaire.question5 %> ",
      part: val5,
      note: 1,
      "color": am4core.color('#B6D239')
    },

  ];


  var series = chart.series.push(new am4charts.PieSeries());
  series.dataFields.value = "part";
  series.dataFields.radiusValue = "note";
  series.dataFields.category = "choice";
  series.slices.template.propertyFields.fill = "color";
  series.colors.step = 3;
  series.labels.template.disabled = true;
  series.ticks.template.disabled = true;
  series.hiddenState.properties.endAngle = -90;


  series.slices.template.tooltipText = "";


  var seriestot = charttot.series.push(new am4charts.PieSeries());
  seriestot.dataFields.value = "part";
  seriestot.dataFields.radiusValue = "note";
  seriestot.dataFields.category = "choice";
  seriestot.slices.template.propertyFields.fill = "color";
  seriestot.colors.step = 3;
  seriestot.labels.template.disabled = true;
  seriestot.ticks.template.disabled = true;
  seriestot.hiddenState.properties.endAngle = -90;
  // Put a thick white border around each Slice
  //seriestot.slices.template.stroke = am4core.color("#000");
  //seriestot.slices.template.strokeWidth = 2;
  //seriestot.slices.template.strokeOpacity = 1;

  seriestot.slices.template.fillOpacity = 0.2;

  //chart.legend = new am4charts.Legend();
});

</script>

app/views/home/index.html.erb
<div class="jumbotron bg-transparent text-center rounded-0 mb-5">
    <h1>Mesurez votre qualité de vie</h1>
    <p>
    Vous souhaitez mesurer votre qualité de vie ?<br>
    ATEV vous propose de faire le test en quelques minutes grâce au Qualiviscope.
    </p>
    <%= link_to 'Démarrer', '#secondContainer', class: 'btn btn-lg btn-dark rounded-pill' %>
</div>

<div id="secondContainer" class="mb-5">
    <h1>Comment ça marche ?</h1>
    <h5 class="mb-5">En quelques minutes, vous pouvez définir votre qualité de vie. 4 étapes sont nécessaires.</h5>

    <div class="row">
        <div class="col-md-4">
            <%= image_tag "etape1.jpg", alt: "Etape 1", class: "img-fluid mb-5" %>
            <h4>Étape 1 : Mes 5 éléments et leurs importances</h4>
            <p>Définissez les 5 éléments essentiels pour votre bonheur et évaluez comment ces éléments influencent votre vie.</p>
        </div>

        <div class="col-md-4">
            <%= image_tag "etape2.jpg", alt: "Etape 2", class: "img-fluid mb-5" %>
            <h4>Étape 2 : Mon niveau de satisfaction</h4>
            <p>Notez l'état de ces éléments dans votre vie actuelle.</p>
        </div>

        <div class="col-md-4">
            <%= image_tag "etape3.jpg", alt: "Etape 3", class: "img-fluid mb-5" %>
            <h4>Etape 3 : Mon score de qualité de vie</h4>
            <p>Voilà grâce aux étapes précédentes vous obtenez votre Qualiviscore : votre score de qualité de vie sur 100 !</p>
        </div>
    </div>
    <p class="text-center my-4">
    <%= link_to 'J\'ai compris !', new_questionnaire_path, class: 'btn btn-lg btn-dark rounded-pill' %>
    </p>
</div>

app/views/questionnaires/edit.html.erb
<%= render 'form', questionnaire: @questionnaire %>

<%= link_to 'Show', @questionnaire %> |
<%= link_to 'Back', questionnaires_path %>

app/views/questionnaires/index.html.erb
<p id="notice"><%= notice %></p>
<h1 class="text-center my-5"> Mes questionnaires</h1>



<% @questionnaires.each do |questionnaire| %>
<div class="table-responsive">
    <table class="table table-bordered table-striped">
        <thead class="thead-dark">
            <th colspan="6">
                <div class="d-flex justify-content-between align-items-center">
                    Questionnaire n°<%= questionnaire.id %>
                    <div>
                    <%= link_to 'Voir', questionnaire, class: 'btn btn-success rounded-0' %>
                    <%= link_to 'Editer', edit_questionnaire_path(questionnaire), class: 'btn btn-primary rounded-0' %>
                    <%= link_to 'Supprimer', questionnaire, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger rounded-0' %>
                    </div>
                </div>
            </th>
        </thead>
        <thead>
            <tr>

                <th scope="col">Question 1</th>
                <th scope="col">Question 2</th>
                <th scope="col">Question 3</th>
                <th scope="col">Question 4</th>
                <th scope="col">Question 5</th>
            </tr>
        </thead>

        <tbody>
            <tr>
                <td><%= questionnaire.question1 %></td>
                <td><%= questionnaire.question2 %></td>
                <td><%= questionnaire.question3 %></td>
                <td><%= questionnaire.question4 %></td>
                <td><%= questionnaire.question5 %></td>


            </tr>
        </tbody>

        <thead>
            <tr>
                <th scope="col">Importance 1</th>
                <th scope="col">Importance 2</th>
                <th scope="col">Importance 3</th>
                <th scope="col">Importance 4</th>
                <th scope="col">Importance 5</th>


            </tr>
        </thead>       
        <tbody>
            <tr>
                <td><%= questionnaire.importance1 %></td>
                <td><%= questionnaire.importance2 %></td>
                <td><%= questionnaire.importance3 %></td>
                <td><%= questionnaire.importance4 %></td>
                <td><%= questionnaire.importance5 %></td>

            </tr>
        </tbody>
    </table>
</div>
<% end %>

<br>

<%= link_to 'Nouveau questionnaire', new_questionnaire_path, class: 'btn btn-dark rounded-0' %>

app/views/questionnaires/new.html.erb
<!-- <h1 class="questionnaire-title">Nouveau questionnaire</h1> -->

<%= render 'form', questionnaire: @questionnaire %>